spring.application.name=Employee_Management

# Railway Port
server.port=${PORT:8085}

# TiDB MySQL Connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/employee_management?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
spring.datasource.username=1Yuvh4X2bUL9uB4.root
spring.datasource.password=mdyhODfDia9DDxmh

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true